name: Test
on:
  push:
    paths-ignore:
      - "**.md"
      - LICENSE
    branches:
      - ci
      - master

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jre
      - uses: asdf-vm/actions/plugin-test@v1
        with:
          command: eval tigervnc -? 2>&1 | grep X509Vnc
